# Generated by Django 4.2.7 on 2023-12-10 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0005_query_answer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
