# Generated by Django 4.2.7 on 2023-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='payment_category',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10),
        ),
    ]
