# Generated by Django 4.2.7 on 2023-12-03 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("video_app", "0002_remove_certificate_date_issued"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="certificates/"
            ),
            preserve_default=False,
        ),
    ]
