# Generated by Django 4.2.7 on 2023-12-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_app", "0003_certificate_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                default="F:\\CSE\\CSE471\\Lab\x0ber3\\CSE471\\media\\certificates\\certificate.pdf",
                upload_to="certificates/",
            ),
        ),
    ]
