# Generated by Django 4.2.7 on 2023-12-03 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_app", "0004_alter_certificate_pdf_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="pdf_file",
        ),
    ]
