# Generated by Django 4.2.7 on 2023-12-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_app", "0006_studentcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="course_playlist",
            field=models.CharField(default="", max_length=255),
        ),
    ]
