# Generated by Django 4.2.7 on 2023-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_app", "0007_studentcourse_course_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="type_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
